// Descriptions grounded in the corresponding public/figures asset.
// Decision links use existing records; no screenshot establishes unseen behavior.
export const figureStories: Record<string, { title: string; caption: string; alt: string; decision?: string }> = {
  "marginalia-2026-10-06.png": { title: "Workspace overview", caption: "Workspace overview with a recent research entry, a recent PDF and the New research action. This capture shows orientation, not an answer or citation.", alt: "Marginalia workspace with recent research and document sections." },
  "marginalia-2026-10-06-134149.png": { title: "Research spaces", caption: "Research list with a workspace entry and the New workspace action. The page groups work by research space.", alt: "Marginalia research list with a rainfall workspace and New workspace button." },
  "marginalia-2026-10-06-134203.png": { title: "Document upload", caption: "Document library with a research selector, PDF file input and Upload PDF action. Successful extraction is evidenced in the repository decision, not by this still.", alt: "Marginalia document upload form with research and PDF inputs.", decision: "marginalia-unpdf-swap" },
  "marginalia-2026-10-06-134215.png": { title: "Account settings", caption: "Settings view with theme controls and profile fields. The OAuth decision explains the account boundary separately.", alt: "Marginalia settings page with theme choices and profile fields.", decision: "marginalia-reject-unknown-oauth" },
  "space-tourism-2026-10-06.png": { title: "Home composition", caption: "Desktop home view with numbered navigation, Earth imagery and the Explore action. Design supplied by Frontend Mentor.", alt: "Space Tourism desktop home with Earth background, navigation and Explore link." },
  "space-tourism-2026-10-06-134326.png": { title: "Moon selected", caption: "Destination view with Moon selected and the other destination controls beside it. A selected appearance does not establish an ARIA tabs pattern.", alt: "Space Tourism destination view showing the Moon and four destination controls." },
  "space-tourism-2026-10-06-134336.png": { title: "Mars selected", caption: "The same destination composition with Mars selected. The image and text change with the local selection.", alt: "Space Tourism destination view showing Mars.", decision: "space-tourism-shorten-image-transitions" },
  "space-tourism-2026-10-06-134347.png": { title: "Crew portrait", caption: "Crew view with Douglas Hurley and a visible focus outline on the navigation link. Imported portrait assets are explained in the linked decision.", alt: "Space Tourism crew page with commander Douglas Hurley.", decision: "space-tourism-import-crew-assets" },
  "space-tourism-2026-10-06-134355.png": { title: "Technology selection", caption: "Technology view with Launch vehicle selected using numbered controls and a portrait image.", alt: "Space Tourism technology page with Launch vehicle and three numbered controls." },
  "fx-2026-10-06.png": { title: "Conversion result", caption: "Captured example: sending 1,000 USD displays 892.54 EUR. These are captured values, not current exchange rates.", alt: "Foreign Exchange Checker showing 1,000 USD converted to 892.54 EUR.", decision: "foreign-exchange-checker-format-receive-input" },
  "fx-2026-10-06-134550.png": { title: "History view", caption: "USD/EUR history with the one-month range selected. The displayed statistics and plotted history are separate requests in the source.", alt: "Foreign Exchange Checker one-month USD/EUR history chart." },
  "fx-2026-10-06-134601.png": { title: "Currency comparison", caption: "Comparison list for an amount of 1,000 USD. A desktop screenshot notification obscures part of this capture; those obscured values are not interpreted.", alt: "Foreign Exchange Checker currency comparison with part of the list obscured by a screenshot notification." },
  "fx-2026-10-06-134610.png": { title: "Empty conversion log", caption: "Empty log view beneath the converter. The captured session wording differs from the browser-local persistence in the repository.", alt: "Foreign Exchange Checker showing No conversions logged yet." },
  "fx-2026-10-06-134617.png": { title: "Saved currency pair", caption: "Favorites view with a saved USD to BRL pair. The picker and saved-pair behavior are separate interactions.", alt: "Foreign Exchange Checker favorites showing a saved USD to BRL pair.", decision: "foreign-exchange-checker-anchor-picker" },
};
export function figureStory(src: string) { return figureStories[src.split("/").pop() ?? ""]; }
